### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [mazipan/bulma-dracula#99]
Hey @mazipan,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by zenorocha** [comment]
Friendly ping ;)

**Comment by mazipan** [comment]
Hi @zenorocha,

Thanks for your offering.
But I don't want to put this repo in the Official Dracula Organization.
You can fork it, but I can not maintain it since I have a limited time.
I just use this for my personal project and might be have no time to fix any issues those not related with my project.

Thank you

**Comment by zenorocha** [comment]
No problem at all @mazipan, I totally understand.
